service-admin-deploy-dev:
  needs: ["service-admin-docker-image-dev"]
  stage: deploy-dev
  extends:
    - .values-service-admin-dev
    - .values-dev-public-service
    - .deploy-service
  only:
    refs:
      - develop
    changes:
      - src/Services/Masa.Tsc.Service.Admin/**/*
      - .gitlab-ci.yml
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "develop"
  #     changes:
  #       - $PROJECT_PATH/**/*
  #       - .gitlab-ci.yml

ui-admin-deploy-dev:
  needs: ["ui-admin-docker-image-dev"]
  stage: deploy-dev
  extends:
    - .values-ui-admin-dev
    - .values-dev-public-ui
    - .deploy-ui
  only:
    refs:
      - develop
    changes:
      - src/Web/Masa.Tsc.Web.Admin.Server/**/*
      - .gitlab-ci.yml
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "develop"
  #     changes:
  #       - $PROJECT_PATH/**/*
  #       - .gitlab-ci.yml