
.values-staging-public-service:
  variables:
    DOCKER_TAG: prd
    NAMESPACE: masa-tsc-staging
    KUBECONFIG: $KUBE_CONFIG_DEV_YDY
    DAPR_ID_PATH: "-staging"
    K8S_REPLICAS: $DEV_REPLICAS
    K8S_FILE: 'devops/k8s.yaml'
    PROJECT_PORT: 80
    DOCKER_IMAGE_NAME: $REGISTRY_URL/$REGISTRY_WAREHOUSE/$PROJECT_NAME:$DOCKER_TAG-$CI_PIPELINE_ID

.values-staging-public-ui:
  variables:
    DOCKER_TAG: prd
    NAMESPACE: masa-tsc-staging
    KUBECONFIG: $KUBE_CONFIG_DEV_YDY
    DAPR_ID_PATH: "-staging"
    K8S_REPLICAS: $DEV_REPLICAS
    K8S_FILE: 'devops/k8s-web.yaml'
    PROJECT_PORT: 443
    DOCKER_IMAGE_NAME: $REGISTRY_URL/$REGISTRY_WAREHOUSE/$PROJECT_NAME:$DOCKER_TAG-$CI_PIPELINE_ID
    
.values-service-admin-staging:
  variables:
    PROJECT_NAME: masa-tsc-service-admin
    PROJECT_PATH: "src/Services/Masa.Tsc.Service.Admin"
    DOMAIN_NAME: tsc-service-admin-staging.masastack.com

.values-ui-admin-staging:
  variables:
    PROJECT_NAME: masa-tsc-ui-admin
    PROJECT_PATH: "src/Web/Masa.Tsc.Web.Admin.Server"
    DOMAIN_NAME: tsc-ui-admin-staging.masastack.com
